"""
train_mednext_phase2.py

Phase 2: MedNeXt-B Student Training with Pseudo-Ground Truth Consensus Masks.

Uses the CLEAN_HIGH_CONFIDENCE and WEAK_COARSE consensus masks generated by the
multi-model ensemble evaluation pipeline as pseudo-ground truth labels.

Key features vs. Phase 1 (train_mednext.py):
  - Reads ensemble_audit_summary.csv to select CLEAN_HIGH_CONFIDENCE cases
    (and optionally WEAK_COARSE with ignore_index=255 boundary masking)
  - Uses consensus masks from results/ensemble_out/<subject_id>_consensus.nii.gz
  - DiceCE loss with ignore_index=255 support for WEAK_COARSE boundary pixels
  - Cosine annealing LR schedule
  - Optional Phase 1 pretrained checkpoint loading (finetuning)
  - Saves best + last checkpoint every epoch
"""

import os
import sys
import argparse
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

# CUDA Optimizations
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

from monai.inferers import sliding_window_inference
from monai.metrics import DiceMetric
from monai.transforms import (
    Compose, LoadImaged, EnsureChannelFirstd, Orientationd, Spacingd,
    ScaleIntensityRanged, SpatialPadd, CropForegroundd, RandCropByPosNegLabeld,
    RandRotated, RandFlipd, RandGaussianNoised,
    RandScaleIntensityd, RandShiftIntensityd, EnsureTyped, AsDiscrete,
)
from monai.data import Dataset, DataLoader, decollate_batch

try:
    from nnunet_mednext import create_mednext_v1
except ImportError:
    try:
        from mednext.create_mednext_v1 import create_mednext_v1
    except ImportError:
        create_mednext_v1 = None

NUM_CLASSES  = 5    # Background + Stomach + Duodenum + Small Bowel + Colon
IGNORE_INDEX = 255  # WEAK_COARSE boundary pixels are ignored in loss


# ---------------------------------------------------------------------------
# Dataset Discovery
# ---------------------------------------------------------------------------

def discover_phase2_dataset(data_dir, audit_csv, ensemble_out_dir, use_weak=False, gold_standard_dir=None):
    """Build image/label pairs using ensemble consensus masks as labels."""
    if not os.path.exists(audit_csv):
        raise FileNotFoundError(f"Audit CSV not found: {audit_csv}")

    # Pre-compute set of gold standard subject IDs for efficient lookup
    gold_standard_ids = set()
    if gold_standard_dir and os.path.exists(gold_standard_dir):
        import glob
        gs_files = glob.glob(os.path.join(gold_standard_dir, "*.nii.gz"))
        for gs_file in gs_files:
            # Extract subject ID from filename (assuming format like SUBJECT_ID.nii.gz or similar)
            filename = os.path.basename(gs_file)
            # Remove .nii.gz extension to get potential subject ID
            subject_id = filename.replace('.nii.gz', '')
            gold_standard_ids.add(subject_id)

    df = pd.read_csv(audit_csv)
    df = df[df['status'] == 'SUCCESS']

    categories = ['CLEAN_HIGH_CONFIDENCE']
    if use_weak:
        categories.append('WEAK_COARSE')

    selected = df[df['triage_category'].isin(categories)]
    print(f"[Phase 2 Dataset] Selected {len(selected):,} subjects:")
    for cat in categories:
        n = (selected['triage_category'] == cat).sum()
        print(f"  - {cat}: {n:,} cases")

    data_pairs = []
    missing_ct = 0
    missing_consensus = 0

    for _, row in selected.iterrows():
        sub_id   = str(row['subject_id'])
        category = row['triage_category']

        ct_path        = os.path.join(data_dir, sub_id, "ct.nii.gz")
        consensus_path = os.path.join(ensemble_out_dir, f"{sub_id}_consensus.nii.gz")

        if not os.path.exists(ct_path):
            missing_ct += 1
            continue
        if not os.path.exists(consensus_path):
            missing_consensus += 1
            continue

        # Check if this is a gold standard sample
        is_gold_standard = sub_id in gold_standard_ids

        data_pairs.append({
            "image":           ct_path,
            "label":           consensus_path,
            "category":        category,
            "subject_id":      sub_id,
            "is_gold_standard": is_gold_standard
        })

    print(f"  Missing CT: {missing_ct} | Missing Consensus: {missing_consensus}")
    print(f"  Final usable pairs: {len(data_pairs):,}")
    if gold_standard_dir:
        gs_count = sum(1 for pair in data_pairs if pair.get("is_gold_standard", False))
        print(f"  Gold standard samples: {gs_count}")
    return data_pairs


# ---------------------------------------------------------------------------
# Transforms
# ---------------------------------------------------------------------------

def get_transforms(roi_size=(96, 96, 96)):
    train_transforms = Compose([
        LoadImaged(keys=["image", "label"]),
        EnsureChannelFirstd(keys=["image", "label"]),
        Orientationd(keys=["image", "label"], axcodes="RAS"),
        Spacingd(keys=["image", "label"], pixdim=(1.5, 1.5, 2.0), mode=("bilinear", "nearest")),
        ScaleIntensityRanged(keys=["image"], a_min=-175, a_max=250, b_min=0.0, b_max=1.0, clip=True),
        CropForegroundd(keys=["image", "label"], source_key="image"),
        SpatialPadd(keys=["image", "label"], spatial_size=roi_size),
        RandCropByPosNegLabeld(
            keys=["image", "label"], label_key="label",
            spatial_size=roi_size, pos=1, neg=1, num_samples=4,
            image_key="image", image_threshold=0,
        ),
        RandRotated(keys=["image", "label"], range_x=0.3, range_y=0.3, range_z=0.3,
                    mode=("bilinear", "nearest"), prob=0.3),
        RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=0),
        RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=1),
        RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=2),
        RandGaussianNoised(keys=["image"], prob=0.15, mean=0.0, std=0.01),
        RandScaleIntensityd(keys=["image"], factors=0.1, prob=0.15),
        RandShiftIntensityd(keys=["image"], offsets=0.1, prob=0.15),
        EnsureTyped(keys=["image", "label"]),
    ])

    val_transforms = Compose([
        LoadImaged(keys=["image", "label"]),
        EnsureChannelFirstd(keys=["image", "label"]),
        Orientationd(keys=["image", "label"], axcodes="RAS"),
        Spacingd(keys=["image", "label"], pixdim=(1.5, 1.5, 2.0), mode=("bilinear", "nearest")),
        ScaleIntensityRanged(keys=["image"], a_min=-175, a_max=250, b_min=0.0, b_max=1.0, clip=True),
        EnsureTyped(keys=["image", "label"]),
    ])

    return train_transforms, val_transforms


# ---------------------------------------------------------------------------
# Loss: DiceCE with ignore_index=255 for WEAK_COARSE boundary masking
# ---------------------------------------------------------------------------

class DiceCEWithIgnoreLoss(nn.Module):
    """
    Combined Dice + Cross-Entropy loss that ignores pixels with label 255.
    Pixels set to IGNORE_INDEX=255 in WEAK_COARSE consensus masks are excluded
    from both CE and Dice computation during training.
    """
    def __init__(self, num_classes=5, ignore_index=255, ce_weight=0.5):
        super().__init__()
        self.num_classes  = num_classes
        self.ignore_index = ignore_index
        self.ce_weight    = ce_weight
        self.dice_weight  = 1.0 - ce_weight

    def forward(self, logits, labels):
        labels_sq = labels.squeeze(1).long()  # (B, X, Y, Z)

        # Cross-Entropy (native ignore_index support)
        ce_loss = F.cross_entropy(logits, labels_sq, ignore_index=self.ignore_index)

        # Dice on valid voxels only
        valid  = (labels_sq != self.ignore_index)
        probs  = F.softmax(logits, dim=1)
        dice_loss = 0.0
        for cls in range(1, self.num_classes):  # skip background
            pred = probs[:, cls, ...] * valid
            gt   = (labels_sq == cls).float() * valid
            intersection = (pred * gt).sum()
            denom        = pred.sum() + gt.sum() + 1e-6
            dice_loss   += 1.0 - (2.0 * intersection) / denom

        dice_loss /= (self.num_classes - 1)
        return self.dice_weight * dice_loss + self.ce_weight * ce_loss


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Phase 2: MedNeXt-B Student Training with Ensemble Pseudo-GT")
    parser.add_argument("--data_dir",         type=str,
                        default="/mnt/scratch/user/chrsong/mp-factory/CancerVerse_dbox")
    parser.add_argument("--audit_csv",        type=str,
                        default="/mnt/scratch/user/chrsong/mp-factory/results/ensemble_audit_summary.csv")
    parser.add_argument("--ensemble_out_dir", type=str,
                        default="/mnt/scratch/user/chrsong/mp-factory/results/ensemble_out")
    parser.add_argument("--out_dir",          type=str,
                        default="/mnt/scratch/user/chrsong/mp-factory/results/mednext_phase2")
    parser.add_argument("--model_id",         type=str,  default="B")
    parser.add_argument("--kernel_size",      type=int,  default=3)
    parser.add_argument("--fold",             type=int,  default=-1)
    parser.add_argument("--num_folds",        type=int,  default=4)
    parser.add_argument("--epochs",           type=int,  default=150)
    parser.add_argument("--batch_size",       type=int,  default=1)
    parser.add_argument("--lr",               type=float, default=1e-4)
    parser.add_argument("--val_interval",     type=int,  default=5)
    parser.add_argument("--max_val_samples",  type=int,  default=50)
    parser.add_argument("--use_weak",         action="store_true",
                        help="Include WEAK_COARSE cases with ignore_index=255 boundary masking")
    parser.add_argument("--pretrained_ckpt",  type=str,  default=None,
                        help="Path to Phase 1 pretrained checkpoint to finetune from")
    parser.add_argument("--gold_standard_dir", type=str, default=None,
                        help="Directory containing gold standard manual annotations for 10x loss weighting")
    args = parser.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    device   = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    num_gpus = torch.cuda.device_count()
    print(f"[Phase 2] Device: {device} | GPUs: {num_gpus} | use_weak: {args.use_weak}")

    data_pairs = discover_phase2_dataset(
        data_dir         = args.data_dir,
        audit_csv        = args.audit_csv,
        ensemble_out_dir = args.ensemble_out_dir,
        use_weak         = args.use_weak,
        gold_standard_dir = args.gold_standard_dir,
    )
    if not data_pairs:
        print("ERROR: No usable data pairs found.")
        sys.exit(1)

    # Train / Val Split
    np.random.seed(42)
    indices = np.random.permutation(len(data_pairs))

    if args.fold >= 0:
        folds       = np.array_split(indices, args.num_folds)
        val_indices = folds[args.fold]
        train_idx   = np.setdiff1d(indices, val_indices)
        train_pairs = [data_pairs[i] for i in train_idx]
        val_pairs   = [data_pairs[i] for i in val_indices]
        print(f"[Fold {args.fold}/{args.num_folds}] Train: {len(train_pairs)} | Val: {len(val_pairs)}")
    else:
        split       = int(0.8 * len(data_pairs))
        train_pairs = [data_pairs[i] for i in indices[:split]]
        val_pairs   = [data_pairs[i] for i in indices[split:]]
        print(f"[80/20 Split] Train: {len(train_pairs)} | Val: {len(val_pairs)}")

    if args.max_val_samples > 0 and len(val_pairs) > args.max_val_samples:
        val_pairs = [val_pairs[i] for i in np.random.choice(
            len(val_pairs), args.max_val_samples, replace=False)]
        print(f"  [Fast Val] Subsampled to {len(val_pairs)} scans.")

    train_tf, val_tf = get_transforms(roi_size=(96, 96, 96))
    train_ds = Dataset(data=train_pairs, transform=train_tf)
    val_ds   = Dataset(data=val_pairs,   transform=val_tf)

    num_workers  = min(16, 4 * max(1, num_gpus))
    train_loader = DataLoader(train_ds, batch_size=args.batch_size,
                              shuffle=True, num_workers=num_workers, pin_memory=True)
    val_loader   = DataLoader(val_ds, batch_size=max(1, num_gpus), num_workers=4)

    # Model
    if create_mednext_v1 is None:
        print("ERROR: Install MedNeXt: pip install git+https://github.com/MIC-DKFZ/MedNeXt.git")
        sys.exit(1)

    model = create_mednext_v1(
        num_input_channels=1, num_classes=NUM_CLASSES,
        model_id=args.model_id, kernel_size=args.kernel_size,
        deep_supervision=False,
    ).to(device)

    if args.pretrained_ckpt and os.path.exists(args.pretrained_ckpt):
        print(f"Loading Phase 1 checkpoint: {args.pretrained_ckpt}")
        model.load_state_dict(
            torch.load(args.pretrained_ckpt, map_location=device), strict=False)

    if num_gpus > 1:
        model = nn.DataParallel(model)

    loss_fn   = DiceCEWithIgnoreLoss(num_classes=NUM_CLASSES,
                                     ignore_index=IGNORE_INDEX, ce_weight=0.5)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-5)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs, eta_min=1e-6)
    scaler    = torch.amp.GradScaler(device_type='cuda')

    dice_metric = DiceMetric(include_background=False, reduction="mean")
    post_pred   = AsDiscrete(argmax=True, to_onehot=NUM_CLASSES)
    post_label  = AsDiscrete(to_onehot=NUM_CLASSES)

    best_val_dice  = -1.0
    best_ckpt_path = os.path.join(args.out_dir, "best_mednext_phase2.pt")
    last_ckpt_path = os.path.join(args.out_dir, "last_mednext_phase2.pt")

    print(f"\n[Phase 2] Starting training ({args.epochs} epochs)...\n")

    for epoch in range(1, args.epochs + 1):
        model.train()
        epoch_loss, step = 0.0, 0

        for batch_data in train_loader:
            step += 1
            inputs = batch_data["image"].to(device)
            labels = batch_data["label"].to(device)
            is_gold_standard = batch_data.get("is_gold_standard", False)
            # Handle case where is_gold_standard might be a tensor or batch
            if isinstance(is_gold_standard, torch.Tensor):
                # If it's a batch, we need to check if any sample in the batch is gold standard
                # For simplicity, we'll apply weighting if any sample in the batch is gold standard
                is_gold_any = is_gold_standard.any().item()
            else:
                is_gold_any = bool(is_gold_standard)

            optimizer.zero_grad()
            with torch.amp.autocast(device_type='cuda'):
                outputs = model(inputs)
                loss    = loss_fn(outputs, labels)

            # Apply 10x weight for gold standard samples
            if is_gold_any:
                loss = loss * 10.0

            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
            epoch_loss += loss.item()

        scheduler.step()
        epoch_loss /= max(step, 1)
        lr_now = scheduler.get_last_lr()[0]
        print(f"Epoch [{epoch:03d}/{args.epochs}] Loss: {epoch_loss:.4f}  LR: {lr_now:.2e}")

        # Save latest checkpoint
        raw = model.module if hasattr(model, "module") else model
        torch.save(raw.state_dict(), last_ckpt_path)

        # Validation
        if epoch % args.val_interval == 0:
            model.eval()
            with torch.no_grad():
                for val_data in val_loader:
                    vi = val_data["image"].to(device)
                    vl = val_data["label"].to(device)

                    with torch.amp.autocast(device_type='cuda'):
                        vo = sliding_window_inference(vi, (96, 96, 96), 4, model)

                    # Remap ignore pixels to background before metric
                    vl_clean = torch.where(vl == IGNORE_INDEX,
                                           torch.zeros_like(vl), vl)
                    vo_post = [post_pred(i) for i in decollate_batch(vo)]
                    vl_post = [post_label(i) for i in decollate_batch(vl_clean)]
                    dice_metric(y_pred=vo_post, y=vl_post)

            mean_val_dice = dice_metric.aggregate().item()
            dice_metric.reset()
            print(f"  --> Val Mean Dice: {mean_val_dice:.4f}")

            if mean_val_dice > best_val_dice:
                best_val_dice = mean_val_dice
                raw = model.module if hasattr(model, "module") else model
                torch.save(raw.state_dict(), best_ckpt_path)
                print(f"  [+] New Best! Dice: {best_val_dice:.4f} -> {best_ckpt_path}")

    print(f"\n[Phase 2 Complete] Best Val Dice: {best_val_dice:.4f}")
    print(f"  Best:  {best_ckpt_path}")
    print(f"  Last:  {last_ckpt_path}")


if __name__ == "__main__":
    main()
