"""
train_mednext_phase2.py

Phase 2: MedNeXt-B Student Training with Pseudo-Ground Truth Consensus Masks.

Uses the CLEAN_HIGH_CONFIDENCE and WEAK_COARSE consensus masks generated by the
multi-model ensemble evaluation pipeline as pseudo-ground truth labels.

Key features vs. Phase 1 (train_mednext.py):
  - Reads ensemble_audit_summary.csv to select CLEAN_HIGH_CONFIDENCE cases
    (and optionally WEAK_COARSE with ignore_index=255 boundary masking)
  - Uses consensus masks from results/ensemble_out/<subject_id>_consensus.nii.gz
  - DiceCE loss with ignore_index=255 support for WEAK_COARSE boundary pixels
  - Cosine annealing LR schedule
  - Optional Phase 1 pretrained checkpoint loading (finetuning)
  - Saves best + last checkpoint every epoch
"""

import os
import sys
import argparse
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.distributed as dist
from torch.utils.data.distributed import DistributedSampler

# CUDA Optimizations
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

from monai.inferers import sliding_window_inference
from monai.metrics import DiceMetric
from monai.transforms import (
    Compose, LoadImaged, EnsureChannelFirstd, Orientationd, Spacingd,
    ScaleIntensityRanged, SpatialPadd, CropForegroundd, RandCropByPosNegLabeld,
    RandRotated, RandFlipd, RandGaussianNoised,
    RandScaleIntensityd, RandShiftIntensityd, EnsureTyped, AsDiscrete,
    ResampleToMatchd,
)
from monai.data import Dataset, DataLoader, decollate_batch

try:
    from nnunet_mednext import create_mednext_v1
except ImportError:
    try:
        from mednext.create_mednext_v1 import create_mednext_v1
    except ImportError:
        create_mednext_v1 = None

# Asymmetric PDCE Loss (asymmetric partial CE + Dice) for recall-optimized training
try:
    from src.segmentation.losses.asymmetric_loss import AsymmetricPDCELoss
except ImportError:
    try:
        import sys as _sys, os as _os
        # __file__ = <vault>/02_Projects/mp-factory/code/training/<this file>
        # dirname x3 -> mp-factory (repo root); x5 -> the vault root holding src/.
        _repo_root = _os.path.dirname(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
        _vault_root = _os.path.dirname(_os.path.dirname(_repo_root))
        if _vault_root not in _sys.path:
            _sys.path.insert(0, _vault_root)
        from src.segmentation.losses.asymmetric_loss import AsymmetricPDCELoss
    except ImportError:
        try:
            # Cluster deployment: asymmetric_loss.py lives beside this script in
            # code/training/ — add that directory and import directly.
            import sys as _sys, os as _os
            _here = _os.path.dirname(_os.path.abspath(__file__))
            if _here not in _sys.path:
                _sys.path.insert(0, _here)
            from asymmetric_loss import AsymmetricPDCELoss
            print("[Loss] AsymmetricPDCELoss loaded from co-located asymmetric_loss.py")
        except ImportError:
            AsymmetricPDCELoss = None

NUM_CLASSES  = 5    # Background + Stomach + Duodenum + Small Bowel + Colon
IGNORE_INDEX = 255  # WEAK_COARSE boundary pixels are ignored in loss


# ---------------------------------------------------------------------------
# Dataset Discovery
# ---------------------------------------------------------------------------

def discover_phase2_dataset(
    data_dir,
    audit_csv,
    ensemble_out_dir,
    autolabel_dir=None,
    use_weak=False,
    gold_standard_dir=None,
    max_cases=0,
    seed=42,
):
    """Build image/label pairs using ensemble consensus masks as labels.

    For CLEAN_HIGH_CONFIDENCE cases: label = *_consensus.nii.gz (labels 0-4).
    For WEAK_COARSE cases: label = *_autolabel.nii.gz (labels 0-4 + IGNORE_INDEX=255
      at conflicting boundary voxels). Falls back to *_consensus.nii.gz with a warning
      if the autolabeler has not been run yet.

    Args:
        autolabel_dir: Directory containing *_autolabel.nii.gz files produced by
            hard_threshold_autolabel.py. Required for correct WEAK_COARSE training.
        max_cases: If > 0, cap total returned cases to this count (reproducible
            subsample via `seed`). Used by the scaling sweep to vary dataset size.
        seed: RNG seed for max_cases subsampling.
    """
    import random as _rnd

    if not os.path.exists(audit_csv):
        raise FileNotFoundError(f"Audit CSV not found: {audit_csv}")

    # Pre-compute set of gold standard subject IDs for efficient lookup
    gold_standard_ids = set()
    if gold_standard_dir and os.path.exists(gold_standard_dir):
        import glob
        gs_files = glob.glob(os.path.join(gold_standard_dir, "*.nii.gz"))
        for gs_file in gs_files:
            subject_id = os.path.basename(gs_file).replace('.nii.gz', '')
            gold_standard_ids.add(subject_id)

    df = pd.read_csv(audit_csv)
    df = df[df['status'] == 'SUCCESS']

    categories = ['CLEAN_HIGH_CONFIDENCE']
    if use_weak:
        categories.append('WEAK_COARSE')

    selected = df[df['triage_category'].isin(categories)]
    print(f"[Phase 2 Dataset] Selected {len(selected):,} subjects:")
    for cat in categories:
        n = (selected['triage_category'] == cat).sum()
        print(f"  - {cat}: {n:,} cases")

    # Warn loudly if WEAK is requested but autolabel_dir was not provided
    if use_weak and not autolabel_dir:
        print(
            "WARNING: --use_weak is set but --autolabel_dir was not provided. "
            "WEAK_COARSE cases will fall back to *_consensus.nii.gz (no ignore masking). "
            "Run hard_threshold_autolabel.py first and pass --autolabel_dir to fix this."
        )

    data_pairs = []
    missing_ct = 0
    missing_consensus = 0
    weak_using_autolabel = 0
    weak_fallback_to_consensus = 0

    for _, row in selected.iterrows():
        sub_id   = str(row['subject_id'])
        category = row['triage_category']

        ct_path        = os.path.join(data_dir, sub_id, "ct.nii.gz")
        consensus_path = os.path.join(ensemble_out_dir, f"{sub_id}_consensus.nii.gz")

        if not os.path.exists(ct_path):
            missing_ct += 1
            continue
        if not os.path.exists(consensus_path):
            missing_consensus += 1
            continue

        # -----------------------------------------------------------------------
        # Route label: CLEAN uses consensus (0-4); WEAK uses autolabel (0-4 + 255)
        # -----------------------------------------------------------------------
        if category == 'WEAK_COARSE' and autolabel_dir:
            autolabel_path = os.path.join(autolabel_dir, f"{sub_id}_autolabel.nii.gz")
            if os.path.exists(autolabel_path):
                label_path = autolabel_path
                weak_using_autolabel += 1
            else:
                # Autolabeler hasn't been run for this subject yet.
                # Fall back to consensus (no 255 masking) but log prominently.
                label_path = consensus_path
                weak_fallback_to_consensus += 1
        else:
            # CLEAN_HIGH_CONFIDENCE, or WEAK without autolabel_dir
            label_path = consensus_path

        is_gold_standard = sub_id in gold_standard_ids

        data_pairs.append({
            "image":            ct_path,
            "label":            label_path,
            "category":         category,
            "subject_id":       sub_id,
            "is_gold_standard": is_gold_standard,
        })

    print(f"  Missing CT: {missing_ct} | Missing Consensus: {missing_consensus}")
    if use_weak:
        print(f"  WEAK cases using autolabel (255 masking): {weak_using_autolabel}")
        if weak_fallback_to_consensus:
            print(
                f"  WARNING: {weak_fallback_to_consensus} WEAK cases fell back to consensus "
                f"(no _autolabel.nii.gz found). Run hard_threshold_autolabel.py to fix."
            )
    print(f"  Final usable pairs: {len(data_pairs):,}")
    if gold_standard_dir:
        gs_count = sum(1 for p in data_pairs if p.get("is_gold_standard", False))
        print(f"  Gold standard samples: {gs_count}")

    # ---- max_cases sub-sampling (for scaling sweep) -------------------------
    if max_cases > 0 and len(data_pairs) > max_cases:
        # Exclude gold-standard cases from the cap so they always train
        gs_pairs      = [p for p in data_pairs if p.get("is_gold_standard", False)]
        non_gs_pairs  = [p for p in data_pairs if not p.get("is_gold_standard", False)]
        rng = _rnd.Random(seed)
        n_non_gs = max(0, max_cases - len(gs_pairs))
        sampled_non_gs = rng.sample(non_gs_pairs, min(n_non_gs, len(non_gs_pairs)))
        data_pairs = gs_pairs + sampled_non_gs
        print(f"  [Scaling sweep] Capped to {len(data_pairs)} cases "
              f"(seed={seed}, max_cases={max_cases})")

    return data_pairs


# ---------------------------------------------------------------------------
# Transforms
# ---------------------------------------------------------------------------

from monai.transforms import MapTransform

class FixLiarLabelAffined(MapTransform):
    """
    CLEAN consensus labels (e.g. from Phase 1) were generated on a resampled 1.5x1.5x2.0 grid.
    However, they were saved with the original CT's affine matrix (which has a smaller spacing like 0.68x0.68x1.5).
    This "liar affine" causes ResampleToMatchd and Spacingd to anatomically misalign the label, shrinking
    the foreground to a tiny corner (causing Dice=0).
    
    WEAK autolabels are still at the original CT spacing and shape, so their affine is correct.
    
    This transform detects CLEAN labels by checking if label.shape != image.shape (before any transforms).
    If it's a CLEAN label, it replaces the label's affine with the correct 1.5x1.5x2.0 affine.
    """
    def __init__(self, keys=["label"], image_key="image", target_spacing=(1.5, 1.5, 2.0)):
        super().__init__(keys)
        self.image_key = image_key
        self.target_spacing = target_spacing

    def __call__(self, data):
        d = dict(data)
        img = d[self.image_key]
        for key in self.keys:
            if key in d:
                lbl = d[key]
                # If shapes mismatch, it means label was ALREADY resampled by Phase 1,
                # but it was saved with the original native affine.
                if lbl.shape != img.shape:
                    from monai.transforms import Spacing
                    spacer = Spacing(pixdim=self.target_spacing)
                    # We just need the affine, so we can pass a dummy tensor or the actual img
                    img_spaced = spacer(img)
                    
                    from monai.data import MetaTensor
                    if isinstance(lbl, MetaTensor):
                        # MetaTensor allows updating the affine
                        lbl.affine = img_spaced.affine
                        if hasattr(lbl, "meta"):
                            lbl.meta["affine"] = img_spaced.affine
                    d[key] = lbl
        return d


def get_transforms(roi_size=(96, 96, 96)):
    # NOTE: ResampleToMatchd MUST appear in BOTH train and val transforms.
    # Consensus labels are generated on a GI-crop sub-volume with a different
    # affine/shape than the full ct.nii.gz (e.g. depth 170 vs 227). Without
    # projecting the label onto the CT grid BEFORE Spacingd, the spatial
    # extents diverge and every crop/metric operates on misaligned voxels
    # -> loss ≈ noise, Dice = 0 for all epochs.
    train_transforms = Compose([
        LoadImaged(keys=["image", "label"]),
        EnsureChannelFirstd(keys=["image", "label"]),
        Orientationd(keys=["image", "label"], axcodes="RAS"),
        # Detect and fix Phase 1 "liar affines" on consensus labels before Spacingd mangles them
        FixLiarLabelAffined(keys=["label"], image_key="image", target_spacing=(1.5, 1.5, 2.0)),
        Spacingd(keys=["image", "label"], pixdim=(1.5, 1.5, 2.0), mode=("bilinear", "nearest")),
        ScaleIntensityRanged(keys=["image"], a_min=-175, a_max=250, b_min=0.0, b_max=1.0, clip=True),
        CropForegroundd(keys=["image", "label"], source_key="image"),
        SpatialPadd(keys=["image", "label"], spatial_size=roi_size),
        RandCropByPosNegLabeld(
            keys=["image", "label"], label_key="label",
            spatial_size=roi_size, pos=1, neg=1, num_samples=4,
            image_key="image", image_threshold=0,
        ),
        RandRotated(keys=["image", "label"], range_x=0.3, range_y=0.3, range_z=0.3,
                    mode=("bilinear", "nearest"), prob=0.3),
        RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=0),
        RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=1),
        RandFlipd(keys=["image", "label"], prob=0.5, spatial_axis=2),
        RandGaussianNoised(keys=["image"], prob=0.15, mean=0.0, std=0.01),
        RandScaleIntensityd(keys=["image"], factors=0.1, prob=0.15),
        RandShiftIntensityd(keys=["image"], offsets=0.1, prob=0.15),
        EnsureTyped(keys=["image", "label"]),
    ])

    val_transforms = Compose([
        LoadImaged(keys=["image", "label"]),
        EnsureChannelFirstd(keys=["image", "label"]),
        Orientationd(keys=["image", "label"], axcodes="RAS"),
        # Detect and fix Phase 1 "liar affines" on consensus labels before Spacingd mangles them
        FixLiarLabelAffined(keys=["label"], image_key="image", target_spacing=(1.5, 1.5, 2.0)),
        Spacingd(keys=["image", "label"], pixdim=(1.5, 1.5, 2.0), mode=("bilinear", "nearest")),
        ScaleIntensityRanged(keys=["image"], a_min=-175, a_max=250, b_min=0.0, b_max=1.0, clip=True),
        EnsureTyped(keys=["image", "label"]),
    ])

    return train_transforms, val_transforms


# ---------------------------------------------------------------------------
# Loss: DiceCE with ignore_index=255 for WEAK_COARSE boundary masking
# ---------------------------------------------------------------------------

class DiceCEWithIgnoreLoss(nn.Module):
    """
    Combined Dice + Cross-Entropy loss that ignores pixels with label 255.
    Pixels set to IGNORE_INDEX=255 in WEAK_COARSE consensus masks are excluded
    from both CE and Dice computation during training.
    """
    def __init__(self, num_classes=5, ignore_index=255, ce_weight=0.5):
        super().__init__()
        self.num_classes  = num_classes
        self.ignore_index = ignore_index
        self.ce_weight    = ce_weight
        self.dice_weight  = 1.0 - ce_weight

    def forward(self, logits, labels):
        labels_sq = labels.squeeze(1).long()  # (B, X, Y, Z)

        # Cross-Entropy (native ignore_index support)
        ce_loss = F.cross_entropy(logits, labels_sq, ignore_index=self.ignore_index)

        # Dice on valid voxels only
        valid  = (labels_sq != self.ignore_index)
        probs  = F.softmax(logits, dim=1)
        dice_loss = 0.0
        for cls in range(1, self.num_classes):  # skip background
            pred = probs[:, cls, ...] * valid
            gt   = (labels_sq == cls).float() * valid
            intersection = (pred * gt).sum()
            denom        = pred.sum() + gt.sum() + 1e-6
            dice_loss   += 1.0 - (2.0 * intersection) / denom

        dice_loss /= (self.num_classes - 1)
        return self.dice_weight * dice_loss + self.ce_weight * ce_loss


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Phase 2: MedNeXt-B Student Training with Ensemble Pseudo-GT")
    parser.add_argument("--data_dir",         type=str,
                        default="/mnt/scratch/user/chrsong/mp-factory/CancerVerse_dbox")
    parser.add_argument("--audit_csv",        type=str,
                        default="/mnt/scratch/user/chrsong/mp-factory/results/ensemble_audit_summary.csv")
    parser.add_argument("--ensemble_out_dir", type=str,
                        default="/mnt/scratch/user/chrsong/mp-factory/results/ensemble_out")
    parser.add_argument("--autolabel_dir",    type=str,
                        default="/mnt/scratch/user/chrsong/mp-factory/results/autolabel_out",
                        help="Directory of *_autolabel.nii.gz files from hard_threshold_autolabel.py. "
                             "Required for correct WEAK_COARSE training with ignore_index=255.")
    parser.add_argument("--out_dir",          type=str,
                        default="/mnt/scratch/user/chrsong/mp-factory/results/mednext_phase2")
    parser.add_argument("--model_id",         type=str,  default="B")
    parser.add_argument("--kernel_size",      type=int,  default=3)
    parser.add_argument("--fold",             type=int,  default=-1)
    parser.add_argument("--num_folds",        type=int,  default=4)
    parser.add_argument("--epochs",           type=int,  default=150)
    parser.add_argument("--start_epoch",      type=int,  default=1,
                        help="Epoch number to start from (useful when resuming from a checkpoint)")
    parser.add_argument("--batch_size",       type=int,  default=1)
    parser.add_argument("--lr",               type=float, default=1e-4)
    parser.add_argument("--num_workers",      type=int,  default=None,
                        help="Number of DataLoader workers per process. If None, auto-calculated from CPU cores.")
    parser.add_argument("--val_interval",     type=int,  default=5)
    parser.add_argument("--max_val_samples",  type=int,  default=50)
    parser.add_argument("--use_weak",         action="store_true",
                        help="Include WEAK_COARSE cases with ignore_index=255 boundary masking")
    parser.add_argument("--loss_type",        type=str,  default="asymmetric",
                        choices=["asymmetric", "dice_ce"],
                        help="Loss: 'asymmetric' (AsymmetricPDCELoss, default) or 'dice_ce' (legacy DiceCEWithIgnoreLoss)")
    parser.add_argument("--alpha",            type=float, default=2.0,
                        help="Asymmetric FN weight (alpha > beta boosts recall)")
    parser.add_argument("--beta",             type=float, default=1.0,
                        help="Asymmetric FP weight (typically 1.0)")
    parser.add_argument("--pretrained_ckpt",  type=str,  default=None,
                        help="Path to Phase 1 pretrained checkpoint to finetune from")
    parser.add_argument("--gold_standard_dir", type=str, default=None,
                        help="Directory of gold-standard manual annotations (JHU radiologist). "
                             "Cases here receive 10x loss weight and are always included in "
                             "the training set regardless of --max_cases.")
    parser.add_argument("--max_cases",        type=int,  default=0,
                        help="If > 0, cap the training set to this many cases (for scaling sweeps). "
                             "Sampled reproducibly with --seed. Gold-standard cases are never capped.")
    parser.add_argument("--seed",             type=int,  default=42,
                        help="Random seed for --max_cases sub-sampling and train/val split.")
    args = parser.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)

    import torch.multiprocessing as mp
    try:
        mp.set_sharing_strategy('file_system')
    except Exception:
        pass

    # Distributed Data Parallel (DDP) / Multi-GPU setup
    is_ddp = "WORLD_SIZE" in os.environ and int(os.environ.get("WORLD_SIZE", "1")) > 1
    if is_ddp:
        dist.init_process_group(backend="nccl")
        local_rank = int(os.environ.get("LOCAL_RANK", 0))
        global_rank = int(os.environ.get("RANK", 0))
        world_size = int(os.environ.get("WORLD_SIZE", 1))
        torch.cuda.set_device(local_rank)
        device = torch.device("cuda", local_rank)
    else:
        local_rank = 0
        global_rank = 0
        world_size = 1
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    def log(*msg, **kw):
        if global_rank == 0:
            print(*msg, **kw, flush=True)

    num_gpus = torch.cuda.device_count()
    log(f"[Phase 2] Device: {device} | Local Rank: {local_rank} | World Size: {world_size} | GPUs (local): {num_gpus} | use_weak: {args.use_weak}")

    data_pairs = discover_phase2_dataset(
        data_dir          = args.data_dir,
        audit_csv         = args.audit_csv,
        ensemble_out_dir  = args.ensemble_out_dir,
        autolabel_dir     = args.autolabel_dir,
        use_weak          = args.use_weak,
        gold_standard_dir = args.gold_standard_dir,
        max_cases         = args.max_cases,
        seed              = args.seed,
    )
    if not data_pairs:
        log("ERROR: No usable data pairs found.")
        sys.exit(1)

    # Train / Val Split (use --seed for reproducibility)
    np.random.seed(args.seed)
    indices = np.random.permutation(len(data_pairs))

    if args.fold >= 0:
        folds       = np.array_split(indices, args.num_folds)
        val_indices = folds[args.fold]
        train_idx   = np.setdiff1d(indices, val_indices)
        train_pairs = [data_pairs[i] for i in train_idx]
        val_pairs   = [data_pairs[i] for i in val_indices]
        log(f"[Fold {args.fold}/{args.num_folds}] Train: {len(train_pairs)} | Val: {len(val_pairs)}")
    else:
        split       = int(0.8 * len(data_pairs))
        train_pairs = [data_pairs[i] for i in indices[:split]]
        val_pairs   = [data_pairs[i] for i in indices[split:]]
        log(f"[80/20 Split] Train: {len(train_pairs)} | Val: {len(val_pairs)}")

    if args.max_val_samples > 0 and len(val_pairs) > args.max_val_samples:
        val_pairs = [val_pairs[i] for i in np.random.choice(
            len(val_pairs), args.max_val_samples, replace=False)]
        log(f"  [Fast Val] Subsampled to {len(val_pairs)} scans.")

    train_tf, val_tf = get_transforms(roi_size=(96, 96, 96))
    train_ds = Dataset(data=train_pairs, transform=train_tf)
    val_ds   = Dataset(data=val_pairs,   transform=val_tf)

    # DataLoader CPU workers allocation
    num_cpus = os.cpu_count() or 4
    if args.num_workers is not None:
        num_workers = args.num_workers
    else:
        if is_ddp:
            num_workers = min(16, max(2, num_cpus // max(1, torch.cuda.device_count())))
        else:
            num_workers = min(16, 4 * max(1, num_gpus))
    log(f"[Phase 2] DataLoader workers per process: {num_workers} (total allocated CPUs on node: {num_cpus})")

    if is_ddp:
        train_sampler = DistributedSampler(
            train_ds, num_replicas=world_size, rank=global_rank, shuffle=True, seed=args.seed
        )
        train_loader = DataLoader(
            train_ds, batch_size=args.batch_size, sampler=train_sampler,
            num_workers=num_workers, pin_memory=True, persistent_workers=(num_workers > 0)
        )
    else:
        train_sampler = None
        train_loader = DataLoader(
            train_ds, batch_size=args.batch_size, shuffle=True,
            num_workers=num_workers, pin_memory=True, persistent_workers=(num_workers > 0)
        )
    val_loader = DataLoader(val_ds, batch_size=max(1, num_gpus), num_workers=min(4, num_workers))

    # Model
    if create_mednext_v1 is None:
        log("ERROR: Install MedNeXt: pip install git+https://github.com/MIC-DKFZ/MedNeXt.git")
        sys.exit(1)

    model = create_mednext_v1(
        num_input_channels=1, num_classes=NUM_CLASSES,
        model_id=args.model_id, kernel_size=args.kernel_size,
        deep_supervision=False,
    ).to(device)

    if args.pretrained_ckpt and os.path.exists(args.pretrained_ckpt):
        log(f"Loading Phase 1/checkpoint: {args.pretrained_ckpt}")
        model.load_state_dict(
            torch.load(args.pretrained_ckpt, map_location=device), strict=False)

    if is_ddp:
        model = nn.parallel.DistributedDataParallel(
            model, device_ids=[local_rank], output_device=local_rank, find_unused_parameters=True
        )
    elif num_gpus > 1:
        model = nn.DataParallel(model)

    # --- Loss selection ---
    if args.loss_type == "asymmetric":
        if AsymmetricPDCELoss is None:
            log("WARNING: AsymmetricPDCELoss import failed; falling back to DiceCEWithIgnoreLoss.")
            loss_fn = DiceCEWithIgnoreLoss(num_classes=NUM_CLASSES,
                                           ignore_index=IGNORE_INDEX, ce_weight=0.5)
        else:
            log(f"[Loss] AsymmetricPDCELoss(alpha={args.alpha}, beta={args.beta}, "
                f"ignore_index={IGNORE_INDEX})")
            loss_fn = AsymmetricPDCELoss(
                apply_softmax=True,
                ce_weight=0.5,
                dice_weight=1.0,
                alpha=args.alpha,
                beta=args.beta,
                ignore_index=IGNORE_INDEX,
            )
    else:
        log(f"[Loss] DiceCEWithIgnoreLoss(ignore_index={IGNORE_INDEX})")
        loss_fn = DiceCEWithIgnoreLoss(num_classes=NUM_CLASSES,
                                       ignore_index=IGNORE_INDEX, ce_weight=0.5)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-5)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs, eta_min=1e-6)

    # If resuming from a later epoch, advance the LR scheduler accordingly
    if args.start_epoch > 1:
        log(f"[Phase 2] Resuming at epoch {args.start_epoch}: advancing LR scheduler {args.start_epoch - 1} steps...")
        for _ in range(1, args.start_epoch):
            scheduler.step()

    try:
        scaler = torch.cuda.amp.GradScaler()
    except Exception:
        scaler = torch.amp.GradScaler('cuda')

    dice_metric = DiceMetric(include_background=False, reduction="mean")
    post_pred   = AsDiscrete(argmax=True, to_onehot=NUM_CLASSES)
    post_label  = AsDiscrete(to_onehot=NUM_CLASSES)

    best_val_dice  = -1.0
    best_ckpt_path = os.path.join(args.out_dir, "best_mednext_phase2.pt")
    last_ckpt_path = os.path.join(args.out_dir, "last_mednext_phase2.pt")

    import hashlib
    _script_hash = hashlib.md5(open(__file__, "rb").read()).hexdigest()[:8]
    log(f"\n[Phase 2] Starting training (epochs {args.start_epoch} -> {args.epochs})...")
    log(f"[Phase 2] Script hash: {_script_hash}  (must match local: run git log --oneline -1 to verify cluster pulled latest)\n")

    for epoch in range(args.start_epoch, args.epochs + 1):
        if is_ddp and train_sampler is not None:
            train_sampler.set_epoch(epoch)
        model.train()
        epoch_loss, step = 0.0, 0

        for batch_data in train_loader:
            step += 1
            inputs = batch_data["image"].to(device)
            labels = batch_data["label"].to(device)
            is_gold_standard = batch_data.get("is_gold_standard", False)
            if isinstance(is_gold_standard, torch.Tensor):
                is_gold_any = is_gold_standard.any().item()
            else:
                is_gold_any = bool(is_gold_standard)

            optimizer.zero_grad()
            with torch.amp.autocast(device_type='cuda'):
                outputs = model(inputs)
                loss    = loss_fn(outputs, labels)

            # Apply 10x weight for gold standard samples
            if is_gold_any:
                loss = loss * 10.0

            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
            epoch_loss += loss.item()

        scheduler.step()
        epoch_loss /= max(step, 1)
        lr_now = scheduler.get_last_lr()[0]
        log(f"Epoch [{epoch:03d}/{args.epochs}] Loss: {epoch_loss:.4f}  LR: {lr_now:.2e}")

        # Save latest checkpoint (rank 0 only)
        if global_rank == 0:
            raw = model.module if hasattr(model, "module") else model
            torch.save(raw.state_dict(), last_ckpt_path)

        # Validation (rank 0 only, all ranks synchronized)
        if epoch % args.val_interval == 0:
            if is_ddp:
                dist.barrier()
            if global_rank == 0:
                raw = model.module if hasattr(model, "module") else model
                raw.eval()
                with torch.no_grad():
                    for val_data in val_loader:
                        vi = val_data["image"].to(device)
                        vl = val_data["label"].to(device)

                        with torch.amp.autocast(device_type='cuda'):
                            vo = sliding_window_inference(vi, (96, 96, 96), 4, raw)

                        if vo.shape[-3:] != vl.shape[-3:]:
                            import warnings
                            warnings.warn(
                                f"[Val] Unexpected shape mismatch after ResampleToMatchd: "
                                f"pred {vo.shape[-3:]} vs label {vl.shape[-3:]}. "
                                "Falling back to trilinear interpolation — check val_transforms.",
                                RuntimeWarning, stacklevel=2,
                            )
                            vo = torch.nn.functional.interpolate(
                                vo.float(), size=vl.shape[-3:],
                                mode="trilinear", align_corners=False,
                            )

                        vl_clean = torch.where(vl == IGNORE_INDEX,
                                               torch.zeros_like(vl), vl)
                        vo_post = [post_pred(i) for i in decollate_batch(vo)]
                        vl_post = [post_label(i) for i in decollate_batch(vl_clean)]
                        dice_metric(y_pred=vo_post, y=vl_post)

                mean_val_dice = dice_metric.aggregate().item()
                dice_metric.reset()
                log(f"  --> Val Mean Dice: {mean_val_dice:.4f}")

                if mean_val_dice > best_val_dice:
                    best_val_dice = mean_val_dice
                    torch.save(raw.state_dict(), best_ckpt_path)
                    log(f"  [+] New Best! Dice: {best_val_dice:.4f} -> {best_ckpt_path}")
            if is_ddp:
                dist.barrier()

    log(f"\n[Phase 2 Complete] Best Val Dice: {best_val_dice:.4f}")
    log(f"  Best:  {best_ckpt_path}")
    log(f"  Last:  {last_ckpt_path}")
    if is_ddp:
        dist.destroy_process_group()


if __name__ == "__main__":
    main()
